# Bước 1: Load dữ liệu

In [1]:
# khai báo thư viện
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Đọc dữ liệu
df = pd.read_excel("DatasetOfficial.xlsx")
df.head()

,user_id,event_time_utc,app_version,country,event_name,level,result,booster_used,ad_format,ad_revenue_usd,iap_revenue_usd
0,U0001,2025-10-15T14:17:00Z,1.2.8,IN,first_open,0,NaN,NaN,NaN,0.0,0.0
1,U0001,2025-10-15T14:28:00Z,1.2.8,IN,level_start,1,NaN,NaN,NaN,0.0,0.0
2,U0001,2025-10-15T14:28:45Z,1.2.8,IN,level_end,1,win,NaN,NaN,0.0,0.0
3,U0001,2025-10-15T14:30:06Z,1.2.8,IN,level_start,2,NaN,NaN,NaN,0.0,0.0
4,U0001,2025-10-15T14:31:04Z,1.2.8,IN,level_end,2,lose,NaN,NaN,0.0,0.0

# Bước 2: Kiểm tra tổng quan dữ liệu

In [3]:
# Tổng quan
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85008 entries, 0 to 85007
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          85008 non-null  object
 1   event_time_utc   85008 non-null  object
 2   app_version      85008 non-null  object
 3   country          85008 non-null  object
 4   event_name       85008 non-null  object
 5   level            85008 non-null  int64
 6   result           34711 non-null  object
 7   booster_used     5187 non-null   object
 8   ad_format        9078 non-null   object
 9   ad_revenue_usd   85008 non-null  float64
 10  iap_revenue_usd  85008 non-null  float64
dtypes: float64(2), int64(1), object(8)
memory usage: 7.1+ MB

In [4]:
# Thống kê
df.describe()

              level  ad_revenue_usd  iap_revenue_usd
count  85008.000000    85008.000000     85008.000000
mean      21.624212        0.001397         0.022266
std       14.517516        0.004893         3.433289
min        0.000000        0.000000         0.000000
25%       10.000000        0.000000         0.000000
50%       19.000000        0.000000         0.000000
75%       32.000000        0.000000         0.000000
max       60.000000        0.039991       999.000000

- lelvel từ 0 -> 60
- Có khách vip mua vật phẩm 999 USD, còn lại khoảng 0->75% số khách không mua gì

In [5]:
# Thống kê các thuộc tính đối tượng
df.describe(include="O")

,user_id,event_time_utc,app_version,country,event_name,result,booster_used,ad_format
count,85008,85008,85008,85008,85008,34711,5187,9078
unique,1000,80503,3,5,6,2,4,2
top,U0638,2025-10-17T12:24:00Z,1.3.0,VN,level_start,win,freeze,interstitial
freq,230,5,29428,21785,34711,20536,1322,6892

# Bước 3: Kiểm tra Missing Value

In [6]:
df.isnull().sum()

user_id                0
event_time_utc         0
app_version            0
country                0
event_name             0
level                  0
result             50297
booster_used       79821
ad_format          75930
ad_revenue_usd         0
iap_revenue_usd        0
dtype: int64

In [7]:
df.head(5)

,user_id,event_time_utc,app_version,country,event_name,level,result,booster_used,ad_format,ad_revenue_usd,iap_revenue_usd
0,U0001,2025-10-15T14:17:00Z,1.2.8,IN,first_open,0,NaN,NaN,NaN,0.0,0.0
1,U0001,2025-10-15T14:28:00Z,1.2.8,IN,level_start,1,NaN,NaN,NaN,0.0,0.0
2,U0001,2025-10-15T14:28:45Z,1.2.8,IN,level_end,1,win,NaN,NaN,0.0,0.0
3,U0001,2025-10-15T14:30:06Z,1.2.8,IN,level_start,2,NaN,NaN,NaN,0.0,0.0
4,U0001,2025-10-15T14:31:04Z,1.2.8,IN,level_end,2,lose,NaN,NaN,0.0,0.0

- Ta quan sát cột result, booster_used, ad_format có nhiều gía trị trống.
- Và chỉ có giá trị khi cột event_name có giá trị tương ứng. 

--- 

- ví dụ: cột result chỉ có giá trị khi ở cột event_name có sự kiện level_end

In [8]:
# Vậy khi cột event_name có sự kiện là level_end. Thì bên cột result có dòng nào trống không?
df[
    (df['event_name'] == 'level_end') &
    (
        df['result'].isna() |
        (df['result'] == '')
    )
]

Empty DataFrame
Columns: [user_id, event_time_utc, app_version, country, event_name, level, result, booster_used, ad_format, ad_revenue_usd, iap_revenue_usd]
Index: []

In [9]:
# Vậy khi cột event_name có sự kiện là ad_impression. Thì bên cột ad_format có dòng nào trống không?

df[
    (df['event_name'] == 'ad_impression') &
    (
        df['ad_format'].isna() |
        (df['ad_format'] == '')
    )
]

Empty DataFrame
Columns: [user_id, event_time_utc, app_version, country, event_name, level, result, booster_used, ad_format, ad_revenue_usd, iap_revenue_usd]
Index: []

In [10]:
# Vậy khi cột event_name có sự kiện là booster_use. Thì bên cột booster_used có dòng nào trống không?

df[
    (df['event_name'] == 'booster_use') &
    (
        df['booster_used'].isna() |
        (df['booster_used'] == '')
    )
]

Empty DataFrame
Columns: [user_id, event_time_utc, app_version, country, event_name, level, result, booster_used, ad_format, ad_revenue_usd, iap_revenue_usd]
Index: []

# Bước 4: Kiểm tra Duplicate

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
# Không có duplicate

# Bước 5: Tìm hiểu dữ liệu categrical

In [13]:
# Trong cột phiên bản (app_version) có những giá trị nào, số lượng bao nhiêu.
df["app_version"].value_counts()

app_version
1.3.0    29428
1.3.3    29388
1.2.8    26192
Name: count, dtype: int64

In [14]:
# Trong cột quốc gia (country) có những giá trị nào, số lượng bao nhiêu.
df["country"].value_counts()

country
VN    21785
US    19684
IN    16395
BR    15165
ID    11979
Name: count, dtype: int64

- VN:Việt Nam
- US:Mỹ
- IN:Ấn
- BR:Brasin
- ID:In Đô

In [15]:
# Trong cột vật phẩm sự dụng (booster_used) có những giá trị nào, số lượng bao nhiêu.
df["booster_used"].value_counts()

booster_used
freeze     1322
magnet     1313
sizeup     1287
compass    1265
Name: count, dtype: int64

- freeze: đóng băng thời gian
- magnet: nam châm hút các vật phẩm về
- sizeup: tăng kích thước
- compass: chỉ đường đến vật phẩm

In [16]:
# Trong loại quảng cáo (ad_format) có những giá trị nào, số lượng bao nhiêu.
df["ad_format"].value_counts()

ad_format
interstitial    6892
rewarded        2186
Name: count, dtype: int64

- interstitial: quảng cáo chen ngang game, khi hết màn...
- rewarded: người chơi xem quảng cáo để nhận thưởng...

In [17]:
df["event_name"].value_counts()

event_name
level_start      34711
level_end        34711
ad_impression     9078
booster_use       5187
first_open        1000
iap_purchase       321
Name: count, dtype: int64

- ad_impression: hiển thị quảng cáo
- iap_purchase: người chơi nạp tiền mua vật phẩm

In [18]:
df["result"].value_counts()

result
win     20536
lose    14175
Name: count, dtype: int64

# Bước 6: Feature Engineering

In [19]:
# Chuyển thời gian từ dạng string -> datetime
df['event_time_utc'] = pd.to_datetime(df['event_time_utc'])

In [20]:
df["month"] = df["event_time_utc"].dt.month

In [21]:
df["hour"] = df["event_time_utc"].dt.hour

In [22]:
df["weekday"] = df["event_time_utc"].dt.day_name()

In [23]:
# Cả 3 phiên bản có phát hành từ ngày nào? có song song không hay gối nhau
version_timeline = (
    df.groupby('app_version')
      .agg(
          first_seen=('event_time_utc', 'min'),
          last_seen=('event_time_utc', 'max'),
          users=('user_id', 'nunique')
      )
      .reset_index()
      .sort_values('first_seen')
)

version_timeline

  app_version                first_seen                 last_seen  users
0       1.2.8 2025-10-09 08:05:00+00:00 2025-10-29 15:32:31+00:00    292
1       1.3.0 2025-10-09 08:20:00+00:00 2025-10-31 16:56:20+00:00    347
2       1.3.3 2025-10-09 08:50:00+00:00 2025-10-31 21:31:46+00:00    361

In [24]:
# Kiểm tra xem có người chơi nào, chơi ở 2 phiên bản khác nhau không, họ update giữa chừng.
multi_version_users = df.groupby('user_id')['app_version'].nunique()

multi_version_users[multi_version_users > 1]

Series([], Name: app_version, dtype: int64)

# Bước 7: Phân tích Revenue

In [25]:
# Tổng doanh thu
df["ad_revenue_usd"].sum() + df["iap_revenue_usd"].sum()

np.float64(2011.5359340000007)

- Doanh thu 1000 users được: 2011 Đô($)

In [26]:
# Tạo cột tổng doanh thu
df['total_revenue'] = (
    df['ad_revenue_usd'] +
    df['iap_revenue_usd']
)

In [27]:
# Revenue từ quảng cáo
df["ad_revenue_usd"].sum()

np.float64(118.73593400000001)

In [28]:
# Revenue từ IAP
df["iap_revenue_usd"].sum()

np.float64(1892.8000000000006)

In [29]:
df.loc[df['iap_revenue_usd'] == 999, 'user_id'].unique()

array(['U0005'], dtype=object)

In [30]:
df[df['user_id'] == 'U0005']

,user_id,event_time_utc,app_version,country,event_name,level,result,booster_used,ad_format,ad_revenue_usd,iap_revenue_usd,month,hour,weekday,total_revenue
197,U0005,2025-10-16 10:22:00+00:00,1.3.3,BR,first_open,0,NaN,NaN,NaN,0.000000,0.0,10,10,Thursday,0.000000
198,U0005,2025-10-16 19:54:00+00:00,1.3.3,BR,level_start,1,NaN,NaN,NaN,0.000000,0.0,10,19,Thursday,0.000000
199,U0005,2025-10-16 19:54:10+00:00,1.3.3,BR,booster_use,1,NaN,sizeup,NaN,0.000000,0.0,10,19,Thursday,0.000000
200,U0005,2025-10-16 19:55:54+00:00,1.3.3,BR,level_end,1,win,NaN,NaN,0.000000,0.0,10,19,Thursday,0.000000
201,U0005,2025-10-16 19:56:56+00:00,1.3.3,BR,level_start,2,NaN,NaN,NaN,0.000000,0.0,10,19,Thursday,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,U0005,2025-10-25 12:16:18+00:00,1.3.3,BR,level_end,39,win,NaN,NaN,0.000000,0.0,10,12,Saturday,0.000000
298,U0005,2025-10-25 12:16:22+00:00,1.3.3,BR,ad_impression,39,NaN,NaN,interstitial,0.019336,0.0,10,12,Saturday,0.019336
299,U0005,2025-10-25 12:16:38+00:00,1.3.3,BR,level_start,40,NaN,NaN,NaN,0.000000,0.0,10,12,Saturday,0.000000
300,U0005,2025-10-25 12:17:39+00:00,1.3.3,BR,level_end,40,win,NaN,NaN,0.000000,0.0,10,12,Saturday,0.000000
301,U0005,2025-10-25 12:17:50+00:00,1.3.3,BR,ad_impression,40,NaN,NaN,rewarded,0.027150,0.0,10,12,Saturday,0.027150

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85008 entries, 0 to 85007
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          85008 non-null  object
 1   event_time_utc   85008 non-null  datetime64[ns, UTC]
 2   app_version      85008 non-null  object
 3   country          85008 non-null  object
 4   event_name       85008 non-null  object
 5   level            85008 non-null  int64
 6   result           34711 non-null  object
 7   booster_used     5187 non-null   object
 8   ad_format        9078 non-null   object
 9   ad_revenue_usd   85008 non-null  float64
 10  iap_revenue_usd  85008 non-null  float64
 11  month            85008 non-null  int32
 12  hour             85008 non-null  int32
 13  weekday          85008 non-null  object
 14  total_revenue    85008 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(3), int32(2), int64(1), object(8)
memory usage: 9.1+ MB

In [32]:
# Tạo thêm các cột phục vụ tính toán

In [33]:
# Ngày cài game.
install_date = (
    df[df['event_name'] == 'first_open']
    .groupby('user_id')['event_time_utc']
    .min()
    .rename('install_date')
)

df = df.merge(
    install_date,
    on='user_id',
    how='left'
)

In [34]:
# Ngày từ lúc tải game, phục vụ tính độ giữ chân (rêtention)
df['days_since_install'] = (
    df['event_time_utc'].dt.normalize()
    - df['install_date'].dt.normalize()
).dt.days

In [35]:
# Người chơi có nạp tiền không
payer_map = (
    df.groupby('user_id')['iap_revenue_usd']
      .sum()
      .gt(0)
      .astype(int)
)

df['is_payer'] = df['user_id'].map(payer_map)

In [36]:
df['days_since_install'].max()

np.int64(13)

In [40]:
print(df['install_date'].min())
print(df['install_date'].max())
print(df['days_since_install'].max())

2025-10-09 08:05:00+00:00
2025-10-18 21:59:00+00:00
13

In [41]:
# Đếm số users cài theo ngày
(
    df.groupby(df['install_date'].dt.date)['user_id']
      .nunique()
      .sort_index()
)

install_date
2025-10-09     96
2025-10-10    101
2025-10-11    103
2025-10-12     91
2025-10-13     83
2025-10-14     99
2025-10-15    107
2025-10-16    111
2025-10-17     95
2025-10-18    114
Name: user_id, dtype: int64

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85008 entries, 0 to 85007
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             85008 non-null  object
 1   event_time_utc      85008 non-null  datetime64[ns, UTC]
 2   app_version         85008 non-null  object
 3   country             85008 non-null  object
 4   event_name          85008 non-null  object
 5   level               85008 non-null  int64
 6   result              34711 non-null  object
 7   booster_used        5187 non-null   object
 8   ad_format           9078 non-null   object
 9   ad_revenue_usd      85008 non-null  float64
 10  iap_revenue_usd     85008 non-null  float64
 11  month               85008 non-null  int32
 12  hour                85008 non-null  int32
 13  weekday             85008 non-null  object
 14  total_revenue       85008 non-null  float64
 15  install_date        85008 non-null  datetime64[ns, UTC]
 16  days_since_install  85008 non-null  int64
 17  is_payer            85008 non-null  int64
dtypes: datetime64[ns, UTC](2), float64(3), int32(2), int64(3), object(8)
memory usage: 11.0+ MB

In [38]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:12345@localhost:5432/gameapp"
)

df.to_sql(
    "gameapp_data",
    engine,
    if_exists="replace",
    index=False
)

8

In [39]:
df.to_csv("Cleaned_data_gameapp.csv", index=False)